version: "3"

services:
    evileye:
        container_name: evileye
        image: ${EVIL_EYE_IMAGE}
        ports:
            - 50051:50051
        environment:
            DB_FILE: ${DATABASEFILE}
